#!/bin/bash

echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║                                                               ║"
echo "║              OWNLY - DEPLOYMENT COMMANDS                      ║"
echo "║                                                               ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""
echo "📦 Your project is committed and ready!"
echo ""
echo "Run these commands to deploy:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔹 STEP 1: Push to GitHub"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Option A - Using GitHub CLI (easiest):"
echo ""
echo "  gh auth login"
echo "  gh repo create ownly --public --source=. --remote=origin --push"
echo ""
echo "Option B - Manual:"
echo ""
echo "  # 1. Create repo at: https://github.com/new"
echo "  # 2. Name it: ownly"
echo "  # 3. Then run:"
echo ""
echo "  git remote add origin https://github.com/YOUR_USERNAME/ownly.git"
echo "  git push -u origin main"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔹 STEP 2: Deploy to Vercel"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  npm install -g vercel"
echo "  vercel login"
echo "  vercel --prod"
echo ""
echo "Or deploy via dashboard:"
echo "  1. Go to: https://vercel.com/new"
echo "  2. Import your GitHub repo"
echo "  3. Settings:"
echo "     - Framework: Next.js"
echo "     - Root Directory: apps/web"
echo "  4. Click Deploy"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔹 STEP 3: Set Environment Variables"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "In Vercel Dashboard → Settings → Environment Variables:"
echo ""
echo "  DATABASE_URL=postgresql://..."
echo "  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_..."
echo "  CLERK_SECRET_KEY=sk_..."
echo "  NEXT_PUBLIC_APP_URL=https://your-project.vercel.app"
echo ""
echo "Get free services:"
echo "  • Database: https://neon.tech (free 3GB)"
echo "  • Auth: https://clerk.com (free 10k users)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔹 STEP 4: Initialize Database"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  export DATABASE_URL='postgresql://...'"
echo "  pnpm db:push"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ That's it! Your app will be live!"
echo ""
echo "📚 Detailed guides:"
echo "  • READY_TO_DEPLOY.md"
echo "  • QUICK_DEPLOY.md"
echo "  • DEPLOYMENT_GUIDE.md"
echo ""
echo "🚀 Let's go!"
